version: '3.4'

services:
  mongo:
    container_name: simba-mongo
    image: mongo
    env_file: .env
    restart: always
    networks:
      - simbanet
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  app:
    container_name: simba-app
    restart: always
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    build: .
    ports:
      - '5000:5000'
    networks:
      - simbanet

networks:
  simbanet: