version: '3.4'

services:
  app:
    container_name: simba-app
    restart: always
    env_file: .env
    build: .
    ports:
      - '80:5000'
    networks:
      - simbanet

  mongo:
    container_name: simba-mongo
    image: mongo
    env_file: .env
    networks:
      - simbanet
    ports:
      - '27017:27017'
    volumes:
      - /data/db:/data/db

networks:
  simbanet: